### ISSUE TITLE
Some situations can sever the link between an article and Disqus

### ISSUE THREAD

**Issue by matks** [PrestaShop/prestashop.github.io#620]
With @sam-pires we have identified that since 6 days (= when we added the FAQ), we cannot see anymore the comments posted for the [critical security vulnerability in prestashop modules](https://build.prestashop.com/news/critical-security-vulnerability-in-prestashop-modules/).

So our guess is that modifying an already published blog article severs the link with Disqus, and Disqus is not able to add the new comments into the article.

Example:
https://disqus.com/home/discussion/prestashopbuild/critical_security_vulnerability_in_prestashop_modules_8872/
https://disqus.com/home/discussion/prestashopbuild/critical_security_vulnerability_in_prestashop_modules_24963/
Both comments do not appear on page https://build.prestashop.com/news/critical-security-vulnerability-in-prestashop-modules/

**Comment by ttoine** [comment]
Modifying an article has been done in the past without having this problem.

I talked with Clement and my opinion is that the problem is when people are coming to the article with a link in a newsletter with parameters. Disqus is basing the comment system on the link displayed in the browser, and they might have an issue to filter some parameters from our newsletter system.

When I had notifications about those comments, that was weird to see one comment alone on this page. And when I removed the newsletter tracking parameters and refresh the page, I was back on the regular Disqus comments (a lot in the case of that page).
